apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-catalog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-catalog-backend
  template:
    metadata:
      labels:
        app: games-catalog-backend
    spec:
      containers:
      - name: games-catalog-backend
        image: sebastiancharras/games-catalog-backend
        ports:
        - containerPort: 8082 
        env:
        - name: NODE_PORT
          value: "8082"
        - name: DB_URI
          value: "mongodb://mongodb:27017/"
        - name: JWT_SECRET
          value: secret
