apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-catalog-pvc
  labels:
    app: games-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
